### ISSUE TITLE
Why defql does require Elixir ~> 1.4?

### ISSUE THREAD

**Issue by romul** [fazibear/defql#2]
Elixir 1.3.x is still widely in use and I don't see any restriction why defql would not work with Elixir 1.3.

**Comment by fazibear** [comment]
Defql will work with Elixir 1.3. I'll will change it. I've started developing it on 1.4.

**Comment by fazibear** [comment]
fixed here: https://github.com/fazibear/defql/commit/6ae216246f2f6ef0153cb3ccac87f370a3b4f80e
