### ISSUE TITLE
Can I pass the tablename and get the result in the same function ?

### ISSUE THREAD

**Issue by PaulD1980** [fazibear/defql#9]
Can I pass the query itself and get the result? For example

I want to pass

Select * from user and get the result

Select * from account and get the result.

Or I need to create the function for each table?

**Comment by fazibear** [comment]
Hi,

Don't know if I understand you correctly. Did you try something like this?

```elixir
  defquery get_by_name(table, name, limit) do
    "SELECT * FROM $table WHERE name = $name LIMIT $limit"
  end
```
